version: '3'

services:
  front:
    image: test
    expose:
      - "3500"
    ports:
      - "3500:3500"
    volumes:
      - ./front/client:/home/node/app
      - ./front/client/node_modules
    working_dir: /home/node/app
    command: sh -c "npm run dev"

  back:
    image: back-img
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ./back:/home/node/app
      - ./back/node_modules
    working_dir: /home/node/app
    command: sh -c "node server"


    