version: '3'

services:
  db:
    build: ./database
  #  volumes:
  #    - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      # - MYSQL_ROOT_PASSWORD="1234"
    platform: linux/x86_64
    ports:
      - '3333:3306'
    expose:
      - '3333'


  front:
    build: ./front
    expose:
      - "3500"
    ports:
      - "3500:3500"
    volumes:
      - ./front/client:/home/node/app
      - ./front/client/node_modules
    working_dir: /home/node/app
    command: sh -c "npm run dev"

  back:
    build: ./back
    expose:
      - "4000"
    ports:
      - "4000:4000"
    volumes:
      - ./back:/home/node/app
      - ./back/node_modules
    working_dir: /home/node/app
    command: sh -c "node server"

    # networks:
    #   - some_net

    # depends_on:
    #   - db



networks:
  default:
    external:
      name: some_net
    